import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// One auto-generated sidebar over the whole docs/ tree. Section order and labels
// come from each folder's _category_.json; article order from the per-file
// `sidebar_position` frontmatter. Adding a doc requires no edit here.
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
