// Emits `src/brand/logo.generated.ts` from `assets/logo.svg` (light theme)
// and `assets/logo-dark.svg` (dark theme): the `viewBox` plus the inner
// markup of each file as string literals. The package builds with plain
// `tsc`, so inlining keeps the logo bundler-agnostic (no `?raw` imports).
// Re-run after replacing either SVG: `pnpm gen:logo` (part of `build`).
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, "../src/brand/logo.generated.ts");

const parse = (svg, name) => {
  const open = svg.match(/<svg\b[^>]*>/i);
  const close = svg.lastIndexOf("</svg>");
  if (!open || close < 0) throw new Error(`${name}: not an <svg> document`);
  const viewBox = open[0].match(/viewBox="([^"]+)"/i)?.[1];
  if (!viewBox) throw new Error(`${name}: <svg> needs a viewBox`);
  const inner = svg.slice(open.index + open[0].length, close).trim();
  return { viewBox, inner };
};

const light = parse(await readFile(join(here, "../assets/logo.svg"), "utf8"), "logo.svg");
const dark = parse(await readFile(join(here, "../assets/logo-dark.svg"), "utf8"), "logo-dark.svg");
if (light.viewBox !== dark.viewBox) {
  throw new Error(
    `logo.svg and logo-dark.svg must share a viewBox (${light.viewBox} vs ${dark.viewBox})`,
  );
}

const out =
  "// Generated by scripts/gen-logo.mjs from assets/logo*.svg — do not edit.\n" +
  `export const LOGO_VIEWBOX = ${JSON.stringify(light.viewBox)};\n` +
  `export const LOGO_LIGHT_MARKUP = ${JSON.stringify(light.inner)};\n` +
  `export const LOGO_DARK_MARKUP = ${JSON.stringify(dark.inner)};\n`;

await writeFile(outPath, out, "utf8");
