// Emits `src/styles.generated.ts` holding the react-ui stylesheet as a
// string literal. The custom element adopts it into its shadow root via
// `adoptedStyleSheets`, which needs the CSS text at runtime — generating a
// `.ts` keeps that bundler-agnostic (no `?raw` / `?inline` import magic).
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const cssPath = join(here, "../../react-ui/src/styles.css");
const outPath = join(here, "../src/styles.generated.ts");

const css = await readFile(cssPath, "utf8");
const out =
  "// Generated by scripts/gen-styles.mjs — do not edit.\n" +
  "// The react-ui stylesheet, inlined for shadow-root adoption.\n" +
  `export const REACT_UI_STYLES = ${JSON.stringify(css)};\n`;

await writeFile(outPath, out, "utf8");
